### ISSUE TITLE
JEI Crash "character in path of location: powersuits:Addon: Range Tier 7"

### ISSUE THREAD

**Issue by Enterprise12nx01** [lehjr/MachineMusePowersuits#94] opened 2024-02-01 03:15 UTC
**Version info**
Java version: 1.8.0.401 64
Minecraft Forge version: 43.3.7

**Describe the bug**
Going through jei with this mod installed will cause a crash when you reach its page. i have also seen errors at startup with this mod

**To Reproduce**
1. play the game in 1.19.2 with latest jei and mps
2. scroll through jei
3. crash to desktop

**Expected behavior**
not crashing with jei

**Mod list**
Including versions, provided by crash report if game crashed: listed in crash report!

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in): https://gist.githubusercontent.com/Enterprise12nx01/9d36098266df89d50f6ffecd9d8e52fe/raw/f0aab05097d0391192147397dcf8a43cc0c0754e/gistfile1.txt
Crash report (if issue caused game to crash): https://pastes.io/me2cmkhdjq
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash): NA

**Screenshots**

**Additional context**

**Comment by lehjr** [comment] 2024-02-02 18:29
Can't reproduce with the steps provided.

**Comment by James-P-Bennett** [comment] 2024-02-16 20:05
I'm getting a similar issue when Industrial Foregoing is installed. Looks like a conflicting namespace with the Range addons

**Comment by James-P-Bennett** [comment] 2024-02-18 03:32
Just going to leave this here for reference:
https://github.com/lehjr/MachineMusePowersuits/issues/97
The way addons are being parsed by numina core is causing problems

**Comment by lehjr** [comment] 2024-02-18 14:45
should be fixed in 1.19.2-2.3.9

**Closed by lehjr** 2024-02-18 14:45 UTC
Labels: invalid, incomplete
