### ISSUE TITLE
leggings armor value stuck at zero

### ISSUE THREAD

**Issue by SandwichIsGreat** [lehjr/MachineMusePowersuits#44] opened 2022-01-14 01:22 UTC
Armor no longer being applied after installing sprint assist. Steps to reproduce: Equip armor. install sprint assist. walk. armor value is now 0.

Version:1.16.5
Forge:36.2.23
[latest.log](https://github.com/lehjr/MachineMusePowersuits/files/7867016/latest.log)

**Comment by lehjr** [comment] 2022-01-14 12:15
This is definitely an odd one.  Something off in the attributes being applied. I'll try and work on it today and get it out with the next update:
![2022-01-14_07 12 19](https://user-images.githubusercontent.com/1084367/149513931-0d3c4cb3-ce03-419e-bb8a-0c63f7a9dba2.png)

**Comment by lehjr** [comment] 2022-01-18 12:47
Duplicate of issue #31

**Closed by lehjr** 2022-01-18 12:47 UTC
Labels: bug, duplicate
