### ISSUE TITLE
Armour not correctly working

### ISSUE THREAD

**Issue by FC360D** [lehjr/MachineMusePowersuits#31] opened 2021-10-23 01:03 UTC
I have a every armour piece with energy shield at 100% and advance batteries however the Chest and leggings are ignored for some reason even though both have the energy shields set to 100%.

Edit:
After messing around it seems to be the kinetic generator causing most of the issue as installing it onto the torso causes the armour to be removed and a -0.03 speed when worn on legs which is weird as the torso doesn't go on the leg lol. However the leggings never seem to have any armour even though it has the energy shield so not sure what's going on with that.

**Comment by Santvarg** [comment] 2022-01-09 00:28
I can confirm this, chest armor with max rank battery and shield works fine, breaks when kinetic gen is equipped, shows as leg item with speed bonus but no armor bonus

Legs work up until you put sprint assist on, showing only a speed bonus for legs, but only AFTER taking a step

Both items are broken indefinitely for armor and you must make new ones
[debug.log](https://github.com/lehjr/MachineMusePowersuits/files/7834254/debug.log)
[latest.log](https://github.com/lehjr/MachineMusePowersuits/files/7834255/latest.log)
[2022-01-07-2.log.gz](https://github.com/lehjr/MachineMusePowersuits/files/7834256/2022-01-07-2.log.gz)

Here are the logs from this session:

**Comment by Santvarg** [comment] 2022-01-09 07:36
Additionally, here's my modlist as I see that should be standard
Numina 2.1.16, MPS 2.1.18
![image](https://user-images.githubusercontent.com/11529683/148673463-7885cff4-cee9-40c8-b8c3-604fe8ec83e3.png)

**Comment by lehjr** [comment] 2022-01-18 12:53
Underlying issue is the way the attribute modifiers are applied. Setting with tags bypasses all other settings, so they have to be applied dynamically through the ItemStack sensitive method and has to be applied in a similar fashion with what I already have in the base class otherwise the effect is permanently applied to the player until the next login. I have a fix in the works, I’m just working on balancing the effect between the sprint assist and the kinetic generator.

**Comment by lehjr** [comment] 2022-01-27 01:01
Fixed in latest beta

**Closed by lehjr** 2022-01-27 01:01 UTC
Labels: bug, In progress

**Comment by CrossVas** [comment] 2022-03-12 07:19
Having the same issue playing on the latest [ModularPowersuits-1.16.5-RC-1](https://www.curseforge.com/minecraft/mc-mods/modular-powersuits/files/3677441). 
On previous version (1.12.2) I could go just fine with Sprint Assist and Kinetic Gen working fine and it could provide extra energy. 
The problem is that I can't get Kinetic Gen working correctly.... I can't figure out if it's working in general, because I don't get energy from it when moving. So either Sprint Assist isn't using energy and Kinetic not generating it, either Kinetic Gen generating the same amount of energy to fit perfectly Sprint Assist usage. I'm very confused.
